from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

router = DefaultRouter() # automatically create URI for different API
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)

app_name = 'recipe' # we define the app name so that the reverse function can look for correct
# urls

urlpatterns = [
    path('', include(router.urls)), # pass all request,, all urls generated by default router
    # will be included in url patterns,, if we add new viewsets
    ## we can just register them here

]
